name: guillotine
description: Simple Guillotine menu animation in Flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
